#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -lt 1 ]
then
	echo "WPS in Client Mode..." > /dev/console
	sync
	/bin/wpa_supplicant_cli.sh
	sleep 5
 	source /etc/systemid.conf
        /bin/mqtt_subscribe.lua -i local_$systemid -t $systemid@/# > /dev/null &
	killall mDNSResponder
	/usr/bin/mDNSResponder -f /etc/mDNSResponder.conf
elif [ "$SEEN" -gt 5 ]
then
echo "WPS in AP Mode..." > /dev/console
        source /etc/systemid.conf
   	long=$systemid
	short=${long:4:8}

        uci set wireless.@wifi-iface[0].mode=ap; uci commit wireless; 
        uci set wireless.@wifi-iface[0].ssid=Irdroid-IoT-$short; uci commit wireless;
        uci set wireless.@wifi-iface[0].key=iosysdemo; uci commit wireless;
        uci set network.wifi.proto=static; uci commit network;  
        wifi down
        sleep 1 
	wifi up
	sleep 2
        hostapd_cli wps_pbc
	killall mDNSResponder
	/usr/bin/mDNSResponder -f /etc/mDNSResponder.conf
fi
